# Generated by Django 5.0.6 on 2024-05-28 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementbin',
            name='deadline',
            field=models.DateTimeField(),
        ),
    ]
