# Generated by Django 5.0.6 on 2024-05-28 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0002_alter_requirementbin_deadline'),
        ('utilities', '0007_rename_category_id_requirementtype_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementbin',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category_requirementbin', to='utilities.requirementcategory'),
        ),
    ]
