# Generated by Django 5.0.6 on 2024-05-28 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0003_alter_requirementbin_category'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='requirementbin',
            table='FARMSReqBin',
        ),
    ]
