# Generated by Django 5.0.6 on 2024-05-28 09:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0004_alter_requirementbin_table'),
        ('utilities', '0008_alter_requirementcategory_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementBinContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('requirement_bin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reqbin_reqbincontents', to='utilities.requirementcategory')),
                ('requirement_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reqtype_reqbincontents', to='utilities.requirementtype')),
            ],
            options={
                'db_table': 'FARMSReqBinContent',
                'unique_together': {('requirement_bin', 'requirement_type')},
            },
        ),
    ]
