# Generated by Django 5.0.6 on 2024-05-28 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0005_requirementbincontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementbincontent',
            name='requirement_bin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reqbin_reqbincontents', to='requirements.requirementbin'),
        ),
    ]
