# Generated by Django 5.0.6 on 2024-05-28 11:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0006_alter_requirementbincontent_requirement_bin'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequirementUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('acadhead_remarks', models.TextField(blank=True, null=True)),
                ('revision_count', models.SmallIntegerField(blank=True, null=True)),
                ('submission_type', models.CharField(max_length=50)),
                ('uploader_comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('requirement_bin_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reqbin_reqbincontents', to='requirements.requirementbincontent')),
            ],
            options={
                'db_table': 'FARMSUserReqUploads',
            },
        ),
    ]
