# Generated by Django 5.0.6 on 2024-06-02 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('utilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementcategory',
            name='created_by_faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_faculty_category', to='accounts.fisfaculty'),
        ),
        migrations.AddField(
            model_name='requirementcategory',
            name='modified_by_faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_faculty_category', to='accounts.fisfaculty'),
        ),
        migrations.AddField(
            model_name='requirementtype',
            name='created_by_faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_faculty_requirementtype', to='accounts.fisfaculty'),
        ),
        migrations.AddField(
            model_name='requirementtype',
            name='modified_by_faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_faculty_requirementtype', to='accounts.fisfaculty'),
        ),
        migrations.AddField(
            model_name='schoolyear',
            name='created_by_faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_faculty_schoolyear', to='accounts.fisfaculty'),
        ),
        migrations.AddField(
            model_name='schoolyear',
            name='modified_by_faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_faculty_schoolyear', to='accounts.fisfaculty'),
        ),
        migrations.AddField(
            model_name='semester',
            name='created_by_faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_faculty_semester', to='accounts.fisfaculty'),
        ),
        migrations.AddField(
            model_name='semester',
            name='modified_by_faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_faculty_semester', to='accounts.fisfaculty'),
        ),
    ]
