# Generated by Django 5.0.6 on 2024-05-26 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0003_requirementcategory_alter_semester_school_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementcategory',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category_semester', to='utilities.semester'),
        ),
    ]
