# Generated by Django 5.0.6 on 2024-05-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0004_requirementcategory_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementcategory',
            name='has_child_records',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requirementtype',
            name='has_child_records',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schoolyear',
            name='has_child_records',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='semester',
            name='has_child_records',
            field=models.BooleanField(default=False),
        ),
    ]
