# Generated by Django 5.0.6 on 2024-05-27 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0006_rename_title_requirementtype_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requirementtype',
            old_name='category_id',
            new_name='category',
        ),
        migrations.AlterUniqueTogether(
            name='requirementtype',
            unique_together={('name', 'category')},
        ),
    ]
