# Generated by Django 5.0.6 on 2024-05-28 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0007_rename_category_id_requirementtype_category_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='requirementcategory',
            table='FARMSReqCategory',
        ),
        migrations.AlterModelTable(
            name='requirementtype',
            table='FARMSReqType',
        ),
    ]
