# Generated by Django 5.0.6 on 2024-05-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0008_alter_requirementcategory_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementtype',
            name='is_assigned_to_bin',
            field=models.BooleanField(default=False),
        ),
    ]
